books/urls.py
from django.urls import path

from . import views


app_name = 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.show, name='show'),
    path('add/', views.add, name='add'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

core/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, LogoutView, 
    PasswordResetView, PasswordResetConfirmView,
)
from django.shortcuts import redirect
from django.urls import path, include, reverse_lazy

from .views import permission_denied, register


login_params = {
    'template_name': 'users/login.html',
    'redirect_authenticated_user': True,
}

password_reset_params = {
    'template_name': 'users/password_reset.html',
    'email_template_name': 'users/password_reset/email.html',
    'subject_template_name': 'users/password_reset/subject.txt',
    'success_url': reverse_lazy('login'),
}

password_set_params = {
    'template_name': 'users/password_set.html',
    'post_reset_login': True,
    'success_url': reverse_lazy('root'),
}

urlpatterns = [
    path('', lambda request: redirect('books:index'), name='root'),
    path('login/', LoginView.as_view(**login_params), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('password-reset/', 
         PasswordResetView.as_view(**password_reset_params), 
         name='password_reset'),
    path('password-set/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(**password_set_params),
         name='password_set'),
    
    path('books/', include('books.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
]

handler403 = permission_denied

books/models.py
from django.db import models

class Author(models.Model):
    name = models.CharField('名字', max_length=10)
    email = models.EmailField('電子郵件', unique=True)

    def __str__(self):
        return self.name

class Publish(models.Model):
    name = models.CharField('出版社名稱', max_length=50, unique=True)
    address = models.CharField('地址', max_length=255)

    def __str__(self):
        return self.name

class Classification(models.Model):
    name = models.CharField('分類名稱', max_length=50, unique=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField('標籤名稱', max_length=50, unique=True)

    def __str__(self):
        return self.name

class Book(models.Model):
    name = models.CharField('書名', max_length=50)
    price = models.PositiveIntegerField('價格')
    authors = models.ManyToManyField(Author, verbose_name='作者')
    publish = models.ForeignKey(Publish, models.PROTECT, verbose_name='出版社')
    classification = models.ForeignKey(
        Classification,
        models.PROTECT,
        verbose_name='分類'
    )
    tags = models.ManyToManyField(Tag, verbose_name='標籤')
    introduction = models.TextField('簡介')

    def __str__(self):
        return self.name

books/forms.py
from django import forms

from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        fields = '__all__'
        model = Book

utils/forms.py
from django import forms

class DeleteConfirmForm(forms.Form):
    check = forms.BooleanField(label='您確認要刪除嗎？')

books/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from utils.forms import DeleteConfirmForm
from .forms import BookForm
from .models import Book

@login_required
def index(request):
    books = Book.objects.all()
    return render(request, 'books/index.html', {'books': books})

@login_required
def show(request, pk):
    # try:
    #     book = Book.objects.get(pk=pk)
    # except Exception:
    #     raise Http404

    book = get_object_or_404(Book, pk=pk)
    return render(request, 'books/show.html', {'book': book})

@login_required
@permission_required('books.add_book', raise_exception=True)
def add(request):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, '新增成功')
        return redirect('books:index')

    return render(request, 'books/add.html', {'form': form})

@login_required
@permission_required('books.edit_book', raise_exception=True)
def edit(request, pk):
    book = get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        messages.success(request, '更新成功')
        return redirect('books:index')

    return render(request, 'books/edit.html', {'form': form})

@login_required
@permission_required('books.delete_book', raise_exception=True)
def delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    form = DeleteConfirmForm(request.POST or None)
    if form.is_valid() and form.cleaned_data['check']:
        book.delete()
        messages.success(request, '刪除成功')
        return redirect('books:index')

    return render(request, 'books/delete.html', {'form': form})

core/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render

def permission_denied(request, exception, template_name='403.html'):
    messages.warning(request, '權限不足')
    return redirect('root')

def register(request):
    if request.user.is_authenticated:
        return redirect('root')
        
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        login(request, user)
        messages.success(request, '{} 您好，歡迎使用～'.format(user.username))
        return redirect('root')

    return render(request, 'users/register.html', {'form': form})

templates/books/add.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h2>新增書籍</h2>
      <hr>
      {% include 'shared/_form.html' %}
    </div>
  </div>
{% endblock %}

templates/books/delete.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h2>刪除書籍</h2>
      <hr>
      {% include 'shared/_form.html' %}
    </div>
  </div>
{% endblock %}

templates/books/edit.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h2>更新書籍</h2>
      <hr>
      {% include 'shared/_form.html' %}
    </div>
  </div>
{% endblock %}

templates/books/index.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col">
      {% if perms.books.add_book %}
        <a href="{% url 'books:add' %}" class="btn btn-outline-info float-right">新增書籍</a>
      {% endif %}
      <h2>書籍列表</h2>
      <hr>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          {% for book in books %}
            <tr>
              <td>{{ book.id }}</td>
              <td><a href="{% url 'books:show' book.id %}">{{ book.name }}</a></td>
              <td>{{ book.price }}</td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="3" class="text-center">沒有書籍～</td>
            </tr>
          {% endfor %}
        </tbody>

      </table>
    </div>
  </div>
{% endblock %}

templates/books/show.html
{% extends 'layout.html' %}

{% block main %}
  <h2>#{{ book.id }} {{ book.name }}</h2>
  <hr>
  <p>書名: {{ book.name }}</p>
  <p>價格: {{ book.price }}</p>
  <p>作者: {{ book.authors.all }}</p>
  <p>出版社: {{ book.publish }}</p>
  <p>分類: {{ book.classification }}</p>
  <p>標籤: {{ book.tags.all | join:', ' }}</p>
  <p>簡介: {{ book.introduction | linebreaksbr }}</p>

  <a href="{% url 'books:index' %}" class="btn btn-primary"><< Back</a>
  {% if perms.books.edit_book %}
  <a href="{% url 'books:edit' book.id %}" class="btn btn-info">Edit</a>
  {% endif %}
  {% if perms.books.delete_book %}
  <a href="{% url 'books:delete' book.id %}" class="btn btn-danger">Delete</a>
  {% endif %}
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>Book Store</title>

  {% load static %}
  {% load bootstrap4 %}

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  {% block extra_style %}{% endblock %}
</head>

<body>
  {% include 'shared/_navbar.html' %}

  <div class="container my-3">
    {% bootstrap_messages %}
    {% block main %}{% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  {% block extra_script %}{% endblock %}
</body>

</html>

templates/shared/_form.html
{% load bootstrap4 %}

<form action="" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-outline-info float-right">送出</button>
</form>

templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Book Store</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarToggler">

    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        {% if request.user.is_authenticated %}
          <a class="nav-link" href="{% url 'books:index' %}">書籍列表</a>
        {% endif %}
      </li>
    </ul>

    <ul class="navbar-nav mt-2 mt-lg-0">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">登出（ {{ request.user.username }} ）</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">登入</a>
        </li>
        <span class="navbar-text">/</span>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">註冊</a>
        </li>
      {% endif %}
      </li>
    </ul>
  </div>
</nav>

templates/users/login.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h2>登入</h2>
      <hr>
      {% include 'shared/_form.html' %}
    </div>
  </div>
{% endblock %}

templates/users/password_reset.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h2>忘記密碼</h2>
      <hr>
      {% include 'shared/_form.html' %}
    </div>
  </div>
{% endblock %}

templates/users/password_reset/email.html
Someone asked for password reset for email {{ email }}. Follow the link below: {{ protocol}}://{{ domain }}{% url 'password_set' uidb64=uid token=token %}

templates/users/password_set.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h2>設定密碼</h2>
      <hr>
      {% if validlink %}
        {% include 'shared/_form.html' %}
      {% else %}
        <p>連結已過期，點<a href="{% url 'password_reset' %}">這裡</a>重新要求連結。</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/users/register.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h2>註冊</h2>
      <hr>
      {% include 'shared/_form.html' %}
      <a href="{% url 'login' %}">已經有帳號了嗎？</a>
    </div>
  </div>
{% endblock %}